DROP TABLE IF EXISTS advices;

CREATE TABLE advices (
  id numeric PRIMARY KEY,
  advice text,
  semiRandId numeric,
  shown numeric DEFAULT 0
);

INSERT INTO advices ('id', 'advice', 'semiRandId') VALUES
-- START_QUOTES
(1, 'Add some fucking contrast.'),
(2, 'Have a clear fucking hierarchy.'),
(3, 'Use fucking Helvetica.'),
(4, 'Read a fucking book.'),
(5, 'Get over your fucking self.'),
(6, 'Make it fucking balanced.'),
(7, 'Sketch more fucking ideas.'),
(8, 'Sans-fucking-serif.'),
(9, 'Use a fucking grid system.'),
(10, 'Use more fucking white space.'),
(11, 'Make it fucking consistent.'),
(12, 'Make it fucking asymmetrical.'),
(13, 'Fucking simplify.'),
(14, 'Use a fucking color scheme.'),
(15, 'Have a fucking focal point.'),
(16, 'Fix your fucking letterspacing.'),
(17, 'Rag your fucking type.'),
(18, 'Do your fucking research.'),
(19, 'Fucking communicate something.'),
(20, 'Always use a fucking contract.'),
(21, 'Get fucking inspired.'),
(22, 'Use fucking alignment.'),
(23, 'Use fucking spell check.'),
(24, 'Try a fucking rule line.'),
(25, 'Try removing a fucking rule line.'),
(26, 'Make it fucking bigger.'),
(27, 'Make it fucking smaller.'),
(28, 'Consider your fucking user.'),
(29, 'Don’t be fucking trendy.'),
(30, 'Be fucking decisive.'),
(31, 'Have a fucking concept.'),
(32, 'Hang your fucking quotation marks.'),
(33, 'Watch your fucking intervals.'),
(34, 'Make me fucking care.'),
(35, 'Make it fucking interesting.'),
(36, 'Learn to fucking write.'),
(37, 'Fucking empathize.'),
(38, 'Do your fucking homework.'),
(39, 'Pay attention to fucking detail.'),
(40, 'Stop fucking around.'),
(41, 'Fucking do it again.'),
(42, 'Fucking start over.'),
(43, 'Don’t fucking use comic sans.'),
(44, 'Don’t fucking steal sheep.'),
(45, 'Take a fucking break.'),
(46, 'Fail fucking often.'),
(47, 'Document your fucking successes.'),
(48, 'Write a fucking design brief.'),
(49, 'Don’t use fucking Helvetica.'),
(50, 'Don’t work for a bad fucking design firm.'),
(51, 'Fucking ideate.'),
(52, 'Have a fucking reason.'),
(53, 'Take your fucking time.'),
(54, 'Be fucking honest with yourself.'),
(55, 'Learn to take some fucking criticism.'),
(56, 'Fucking experiment.'),
(57, 'Don’t fucking quit.'),
(58, 'Lose your fucking ego.'),
(59, 'Love your fucking job.'),
(60, 'Pick fucking better clients.'),
(61, 'Ask good fucking questions.'),
(62, 'Think about all the fucking possibilities.'),
(63, 'Don’t fucking procrastinate.'),
(64, 'Be a good fucking person.'),
(65, 'Trust your fucking gut.'),
(66, 'Use one fucking space after a period.'),
(67, 'Make it fucking legible.'),
(68, 'Don’t reinvent the fucking wheel.'),
(69, 'Reinvent the fucking wheel.'),
(70, 'Question fucking everything.'),
(71, 'A computer is a Lite-Brite for bad fucking ideas.'),
(72, 'A computer is just a fucking tool.'),
(73, 'Don’t design in a fucking vacuum.'),
(74, 'It’s all in how you fucking say it.'),
(75, 'Don’t let the fucking text push you around.'),
(76, 'Fucking collaborate.'),
(77, 'Clean up your fucking URLs.'),
(78, 'Encode your fucking ampersands.'),
(79, 'Make it fucking sustainable.'),
(80, 'Break the fucking grid.'),
(81, 'Don’t succumb to fucking cliches.'),
(82, 'Don’t fucking bastardize type.'),
(83, 'Quit your fucking job.'),
(84, 'Concept is fucking king.'),
(85, 'Fucking bastardize type.'),
(86, 'Remove your fucking widows.'),
(87, 'Remove your fucking orphans.'),
(88, 'Take a fucking chance.'),
(89, 'Make fucking mistakes.'),
(90, 'Capitalize on the fucking experience.'),
(91, 'Save fucking often.'),
(92, 'Break the fucking rules.'),
(93, 'Know the fucking rules.'),
(94, 'Form follows fucking function.'),
(95, 'Keep fucking learning.'),
(96, 'Sell your fucking ideas.'),
(97, 'Track your fucking hours.'),
(98, 'Comment your fucking code.'),
(99, 'Drink more fucking coffee.'),
(100, 'Drink less fucking coffee.'),
(101, 'Ask for fucking help.'),
(102, 'Don’t fucking work for free.'),
(103, 'Get a fucking hobby.'),
(104, 'Think fucking laterally.'),
(105, 'The logo is not the fucking brand.'),
(106, 'Get a fucking mentor.'),
(107, 'Learn from your fucking mistakes.'),
(108, 'You won’t know until you fucking try.'),
(109, 'Study your fucking process.'),
(110, 'Learn to fucking say no.'),
(111, 'Learn from your fucking peers.'),
(112, 'Educate your fucking client.'),
(113, 'Identify a fucking need.'),
(114, 'Be more fucking efficient.'),
(115, 'Know when to fucking speak up.'),
(116, 'Buy your fucking fonts.'),
(117, 'Be your fucking self.'),
(118, 'There is no fucking box.'),
(119, 'You can’t polish a fucking turd.'),
(120, 'Fucking network.'),
(121, 'It’s what you fucking leave out.'),
(122, 'Check your fucking separations.'),
(123, 'Give the client what they fucking need.'),
(124, 'Fucking sleep on it.'),
(125, 'Find fucking inspiration everywhere.'),
(126, 'Give a fucking damn.'),
(127, 'Believe in your fucking self.'),
(128, 'Validate your fucking markup.'),
(129, 'Proof your fucking copy.'),
(130, 'Stay up all fucking night.'),
(131, 'Arrive fucking early.'),
(132, 'Go to a fucking conference.'),
(133, 'Take a fucking workshop.'),
(134, 'Don’t fucking work on spec.'),
(135, 'Hire a fucking photographer.'),
(136, 'Know your fucking typefaces.'),
(137, 'Back up your fucking data.'),
(138, 'Read the fucking copy.'),
(139, 'Hire a fucking illustrator.'),
(140, 'The problem contains the fucking solution.'),
(141, 'Learn from your fucking peers.'),
(142, 'Learn from your fucking teachers.'),
(143, 'Learn from your fucking students.'),
(144, 'Learn from other fucking disciplines.'),
(145, 'Work outside of your fucking habits.'),
(146, 'Let limitations drive fucking innovation.'),
(147, 'Make it appropriate but fucking unexpected.'),
(148, 'Be consistent, not fucking predictable.'),
(149, 'Less is fucking more.'),
(150, 'Design is a fucking lifestyle.'),
(151, 'Never fucking assume anything.'),
(152, 'Beautiful things work fucking better.'),
(153, 'Never fucking get caught.'),
(154, 'Respect your fucking colleagues.'),
(155, 'Do it right the first fucking time.'),
(156, 'Work with reliable fucking vendors.'),
(157, 'Measure twice, cut fucking once.'),
(158, 'Constantly fucking challenge yourself.'),
(159, 'Always ask for more fucking money.'),
(160, 'Learn to fucking work for yourself.'),
(161, 'Learn to fucking take advice.'),
(162, 'Be fucking productive.'),
(163, 'Never take no for a fucking answer.'),
(164, 'Show some fucking passion.'),
(165, 'Learn to manage your fucking projects.'),
(166, 'Learn to fucking give advice.'),
(167, 'Solve problems through fucking action.'),
(168, 'Make a fucking difference.'),
(169, 'Promote your fucking self.'),
(170, 'Get up fucking early.'),
(171, 'Get fucking involved.'),
(172, 'Trust your fucking process.'),
(173, 'Be your own fucking boss.'),
(174, 'Open your fucking eyes.'),
(175, 'Always be fucking ready.'),
(176, 'Be fucking observant.'),
(177, 'Practice makes fucking perfect.'),
(178, 'Change your fucking routine.'),
(179, 'Work fucking harder.'),
(180, 'Black is not a fucking color.'),
(181, 'Carve your own fucking path.'),
(182, 'Fucking inspire someone.'),
(183, 'Start a new fucking project.'),
(184, 'Defy fucking convention.'),
(185, 'Tell a fucking story.'),
(186, 'Manage your fucking clients.'),
(187, 'Design is fucking change.'),
(188, 'Thrive where others fucking fail.'),
(189, 'Delight your fucking audience.'),
(190, 'Fall in love with your fucking work.'),
(191, 'Kill the fucking drop shadow.'),
(192, 'Get fucking started.'),
(193, 'You have to fucking want it.'),
(194, 'Seek fucking criticism.'),
(195, 'Don’t play by the fucking rules.'),
(196, 'Don’t make fucking excuses.'),
(197, 'Don’t covet your fucking ideas.'),
(198, 'Give away everything you fucking know.'),
(199, 'First impressions are fucking critical.'),
(200, 'Hire a fucking programmer.'),
(201, 'Learn to adapt or fucking die.'),
(202, 'Stay fucking passionate.'),
(203, 'Own your fucking failures.'),
(204, 'Be fucking authentic.'),
(205, 'Get in over your fucking head.'),
(206, 'Be fucking confident.'),
(207, 'Get fucking focused.'),
(208, 'Fail, fail, and fucking fail again.'),
(209, 'Work with the fucking best.'),
(210, 'It’s not what you say—it’s how you fucking say it.'),
(211, 'Fucking risk everything.'),
(212, 'Learn to fucking improvise.'),
(213, 'Be fucking bold.'),
(214, 'Fire your bad fucking clients.'),
(215, 'Always fucking deliver.'),
(216, 'Be fucking accountable.'),
(217, 'Build fucking credibility.'),
(218, 'Be fucking visionary.'),
(219, 'Co-fucking-create.'),
(220, 'Empathy over fucking ego.'),
(221, 'Envision the fucking future.'),
(222, 'Set your sights fucking higher.'),
(223, 'Make your own fucking rules.'),
(224, 'There is no fucking limit to creativity.');
-- END_QUOTES